# Generated by Django 3.2.9 on 2021-12-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDietas', '0002_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='fdcId',
            field=models.CharField(max_length=200),
        ),
    ]
